version: "3.8"

services:
  ecoflow2influx:
    build:
      context: ./ecoflow2influx
      dockerfile: Dockerfile
    container_name: ecoflow2influx
    depends_on:
      - influxdb
    environment:
      APP_SECRETS_FILE: /run/secrets/app-secrets
      INFLUX_TOKEN_FILE: /run/secrets/influxdb-token
    env_file:
      - ./.env
    secrets:
      - app-secrets
      - influxdb-token


  influxdb:
    image: influxdb:2
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin123
      DOCKER_INFLUXDB_INIT_ORG: nelara
      DOCKER_INFLUXDB_INIT_BUCKET: flotten
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb-token
    secrets:
      - influxdb-token
    volumes:
      - type: volume
        source: influxdb-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb-config
        target: /etc/influxdb2

secrets:
  app-secrets:
    file: ./.app-secrets
  influxdb-token:
    file: ./.influxdb-token

volumes:
  influxdb-data:
  influxdb-config:
